var list = [
  { pattern: /sr-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /bg-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /from-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /via-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /to-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /border-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /divide-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /outline-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /rounded-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /ring-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /table-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /shadow-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /opacity-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /transition-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /duration-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /ease-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /delay-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /animate-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /filter-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /backdrop-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /blur-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /brightness-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /contrast-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /drop-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /grayscale-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /invert-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /saturate-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /sepia-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /flex-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /items-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /content-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /self-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /justify-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /basis-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /grow-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /shrink-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /order-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /col-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /row-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /gap-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /p-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /py-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /px-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /pt-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /pr-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /pb-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /pl-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /m-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /my-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /mx-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /mt-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /mr-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /mb-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /ml-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /appearance-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /resize-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /select-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /snap-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /scroll-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /touch-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /cursor-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /caret-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /accent-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /inline-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /list-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /box-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /float-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /clear-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /isolation-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /object-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /overflow-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /overscroll-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /inset-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /top-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /right-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /bottom-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /left-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /z-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /aspect-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /columns-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /w-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /h-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /fill-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /stroke-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /transform-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /scale-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /rotate-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /origin-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /subpixel-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /non-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /normal-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /slashed-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /lining-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /oldstyle-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /proportional-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /tabular-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /diagonal-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /stacked-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /text-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /line-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /no-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /align-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /whitespace-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /break-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /decoration-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /font-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /tracking-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /leading-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /placeholder-[\w-]*/, variants: ['hover', 'focus'] },
{ pattern: /indent-[\w-]*/, variants: ['hover', 'focus'] }
  // ... other patterns
];

// tailwind.config.js
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  safelist: [],
  darkMode: false,
  theme: {
      extend: {
        colors: {
            wdwhite: '#ecece2',
        },
      },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('daisyui'),
  ],
}
